### ISSUE TITLE
Manifest merger failed : Attribute application@allowBackup

### ISSUE THREAD

**Issue by PetarMarijanovic** [miguelbcr/RxGpsService#6]
Hi, I imported your library via gradle and got this error:

`Manifest merger failed : Attribute application@allowBackup value=(false)`

For now, I "fixed" the issue by adding the `tools:replace="allowBackup"` attribute in my projects manifest, so I can build it and use your lib. 

I think you should remove `allowBackup` attribute from your library's manifest, because you should let the app that uses your lib to decide whether its data can be backed up or not.

Nevertheless, thank you for the great lib! :)

**Comment by miguelbcr** [comment]
Hi @PetarMarijanovic ,
I didn't realize of this.
 I've just released [version 0.1.0 ](https://github.com/miguelbcr/RxGpsService/releases/tag/0.1.0) with this PR.
Thanks!
