### ISSUE TITLE
Is it possible to get updates, without notification builder?

### ISSUE THREAD

**Issue by DalveerSinghDaiya** [miguelbcr/RxGpsService#8]

**Comment by miguelbcr** [comment]
Hi @DalveerSinghDaiya !
sorry for the delay 😔 
I'm afraid not because the notification is needed in order to keep the service alive.

**Comment by DalveerSinghDaiya** [comment]
OK thanks !!



*Dalveer Singh Daiya*
*Add Worth Rise Technologies*
Website : https://www.awrtechnologies.com
Email : <.dalveer@awrtechnologies.com <https://www.awrtechnologies.com/>>
